### ISSUE TITLE
jonathonf/python-3.6' returned a non-zero code: 100

### ISSUE THREAD

**Issue by akniloy6** [joehoeller/computer-vision-container#2]
E: Failed to fetch http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu/dists/bionic/InRelease  403  Forbidden [IP: 91.189.95.83 80]
E: The repository 'http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu bionic InRelease' is not signed.
The command '/bin/sh -c add-apt-repository ppa:jonathonf/python-3.6' returned a non-zero code: 100

**Comment by daddydrac** [comment]
This container has been deprecated in favor of:
https://github.com/joehoeller/NVIDIA-GPU-Tensor-Core-Accelerator-PyTorch-OpenCV
